server:
  port: 1111

spring:
  application:
  name: gateway-service


  cloud:
    gateway:
      routes:
        - id: clientModule
          uri: http://localhost:7070/
          predicates:
            - Path=/v1/**, /test/**


        - id: service1Module
          uri: http://localhost:6061/
          predicates:
            - Path=/v2/**


eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka